"use strict";
exports.__esModule = true;
var pessoa_1 = require("../listaExtra/model/pessoa");
var elevador_1 = require("../listaExtra/model/elevador");
var controleremoto_1 = require("../listaExtra/model/controleremoto");
var televisao_1 = require("../listaExtra/model/televisao");
var tv = new televisao_1.Televisao();
var controle = new controleremoto_1.ControleRemoto(tv);
var pessoa = new pessoa_1.Pessoa('roy', 1.23, '1996-11-21');
var elevador = new elevador_1.Elevador(5, 5);
console.log("PESSOA");
console.log(pessoa.calcularIdade());
pessoa.mostrarDado();
console.log("ELEVADOR");
elevador.descer();
elevador.subir();
elevador.entrar();
elevador.sair();
console.log("CONTROLE");
controle.aumentarVolume();
controle.diminuirVolume();
controle.aumentarVolume();
controle.trocarDeCanal();
controle.trocarParaCanal(6);
console.log(controle.getCanal());
console.log(controle.getVolume());
